import pandas as pd
import pycountry

countries = pd.DataFrame(['Afghanistan', 'Aland Islands', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia, Plurinational State of', 'Bonaire, Sint Eustatius and Saba', 'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil', 'British Indian Ocean Territory', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo', 'Congo, The Democratic Republic of the', 'Cook Islands', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba', 'Curaçao', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard Island and McDonald Islands', 'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Republic of', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Democratic People's Republic of", 'Korea, Republic of', 'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Macedonia, Republic of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia, Federated States of', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestinian Territory, Occupied', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Réunion', 'Romania', 'Russian Federation', 'Rwanda', 'Saint Barthélemy', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin (French part)', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'South Sudan', 'Svalbard and Jan Mayen', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Taiwan, Province of China', 'Tajikistan', 'Tanzania, United Republic of', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Minor Outlying Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, Bolivarian Republic of', 'Viet Nam', 'Virgin Islands, British', 'Virgin Islands, U.S.', 'Wallis and Futuna', 'Yemen', 'Zambia', 'Zimbabwe'])

#A country's List, which consists of properties, e.g. name, alpha3
countries1 = list(pycountry.countries)

#Creating a Dictionary with the Countryname as the key, and the alpha3 as value
def translation():
    country_translation = {}
    for country in countries1:
        name = country.name
        alpha_3 = country.alpha_3
        country_translation[name] = alpha_3
    return country_translation

#Trans Dictioniory sorted, and compared with first countries list
trans = {'Afghanistan': 'AFG',
        'Aland Islands': 'ALA',
        'Albania': 'ALB',
        'Algeria': 'DZA',
        'American Samoa': 'ASM',
        'Andorra': 'AND',
        'Angola': 'AGO',
        'Anguilla': 'AIA',
        'Antarctica': 'ATA',
        'Antigua and Barbuda': 'ATG',
        'Argentina': 'ARG',
        'Armenia': 'ARM',
        'Aruba': 'ABW',
        'Australia': 'AUS',
        'Austria': 'AUT',
        'Azerbaijan': 'AZE',
        'Bahamas': 'BHS',
        'Bahrain': 'BHR',
        'Bangladesh': 'BGD',
        'Barbados': 'BRB',
        'Belarus': 'BLR',
        'Belgium': 'BEL',
        'Belize': 'BLZ',
        'Benin': 'BEN',
        'Bermuda': 'BMU',
        'Bhutan': 'BTN',
        'Bolivia, Plurinational State of': 'BOL',
        'Bonaire, Sint Eustatius and Saba': 'BES',
        'Bosnia and Herzegovina': 'BIH',
        'Botswana': 'BWA',
        'Bouvet Island': 'BVT',
        'Brazil': 'BRA',
        'British Indian Ocean Territory': 'IOT',
        'Brunei Darussalam': 'BRN',
        'Bulgaria': 'BGR',
        'Burkina Faso': 'BFA',
        'Burundi': 'BDI',
        'Cabo Verde': 'CPV',
        'Cambodia': 'KHM',
        'Cameroon': 'CMR',
        'Canada': 'CAN',
        'Cayman Islands': 'CYM',
        'Central African Republic': 'CAF',
        'Chad': 'TCD',
        'Chile': 'CHL',
        'China': 'CHN',
        'Christmas Island': 'CXR',
        'Cocos (Keeling) Islands': 'CCK',
        'Colombia': 'COL',
        'Comoros': 'COM',
        'Congo': 'COG',
        'Congo, The Democratic Republic of the': 'COD',
        'Cook Islands': 'COK',
        'Costa Rica': 'CRI',
        'Croatia': 'HRV',
        'Cuba': 'CUB',
        'Curaçao': 'CUW',
        'Cyprus': 'CYP',
        'Czechia': 'CZE',
        "Côte d'Ivoire": 'CIV',
        'Denmark': 'DNK',
        'Djibouti': 'DJI',
        'Dominica': 'DMA',
        'Dominican Republic': 'DOM',
        'Ecuador': 'ECU',
        'Egypt': 'EGY',
        'El Salvador': 'SLV',
        'Equatorial Guinea': 'GNQ',
        'Eritrea': 'ERI',
        'Estonia': 'EST',
        'Eswatini': 'SWZ',
        'Ethiopia': 'ETH',
        'Falkland Islands (Malvinas)': 'FLK',
        'Faroe Islands': 'FRO',
        'Fiji': 'FJI',
        'Finland': 'FIN',
        'France': 'FRA',
        'French Guiana': 'GUF',
        'French Polynesia': 'PYF',
        'French Southern Territories': 'ATF',
        'Gabon': 'GAB',
        'Gambia': 'GMB',
        'Georgia': 'GEO',
        'Germany': 'DEU',
        'Ghana': 'GHA',
        'Gibraltar': 'GIB',
        'Greece': 'GRC',
        'Greenland': 'GRL',
        'Grenada': 'GRD',
        'Guadeloupe': 'GLP',
        'Guam': 'GUM',
        'Guatemala': 'GTM',
        'Guernsey': 'GGY',
        'Guinea': 'GIN',
        'Guinea-Bissau': 'GNB',
        'Guyana': 'GUY',
        'Haiti': 'HTI',
        'Heard Island and McDonald Islands': 'HMD',
        'Holy See (Vatican City State)': 'VAT',
        'Honduras': 'HND',
        'Hong Kong': 'HKG',
        'Hungary': 'HUN',
        'Iceland': 'ISL',
        'India': 'IND',
        'Indonesia': 'IDN',
        'Iran, Islamic Republic of': 'IRN',
        'Iraq': 'IRQ',
        'Ireland': 'IRL',
        'Isle of Man': 'IMN',
        'Israel': 'ISR',
        'Italy': 'ITA',
        'Jamaica': 'JAM',
        'Japan': 'JPN',
        'Jersey': 'JEY',
        'Jordan': 'JOR',
        'Kazakhstan': 'KAZ',
        'Kenya': 'KEN',
        'Kiribati': 'KIR',
        "Korea, Democratic People's Republic of": 'PRK',
        'Korea, Republic of': 'KOR',
        'Kuwait': 'KWT',
        'Kyrgyzstan': 'KGZ',
        "Lao People's Democratic Republic": 'LAO',
        'Latvia': 'LVA',
        'Lebanon': 'LBN',
        'Lesotho': 'LSO',
        'Liberia': 'LBR',
        'Libya': 'LBY',
        'Liechtenstein': 'LIE',
        'Lithuania': 'LTU',
        'Luxembourg': 'LUX',
        'Macao': 'MAC',
        'Madagascar': 'MDG',
        'Malawi': 'MWI',
        'Malaysia': 'MYS',
        'Maldives': 'MDV',
        'Mali': 'MLI',
        'Malta': 'MLT',
        'Marshall Islands': 'MHL',
        'Martinique': 'MTQ',
        'Mauritania': 'MRT',
        'Mauritius': 'MUS',
        'Mayotte': 'MYT',
        'Mexico': 'MEX',
        'Micronesia, Federated States of': 'FSM',
        'Moldova, Republic of': 'MDA',
        'Monaco': 'MCO',
        'Mongolia': 'MNG',
        'Montenegro': 'MNE',
        'Montserrat': 'MSR',
        'Morocco': 'MAR',
        'Mozambique': 'MOZ',
        'Myanmar': 'MMR',
        'Namibia': 'NAM',
        'Nauru': 'NRU',
        'Nepal': 'NPL',
        'Netherlands': 'NLD',
        'New Caledonia': 'NCL',
        'New Zealand': 'NZL',
        'Nicaragua': 'NIC',
        'Niger': 'NER',
        'Nigeria': 'NGA',
        'Niue': 'NIU',
        'Norfolk Island': 'NFK',
        'North Macedonia': 'MKD',
        'Northern Mariana Islands': 'MNP',
        'Norway': 'NOR',
        'Oman': 'OMN',
        'Pakistan': 'PAK',
        'Palau': 'PLW',
        'Palestine, State of': 'PSE',
        'Panama': 'PAN',
        'Papua New Guinea': 'PNG',
        'Paraguay': 'PRY',
        'Peru': 'PER',
        'Philippines': 'PHL',
        'Pitcairn': 'PCN',
        'Poland': 'POL',
        'Portugal': 'PRT',
        'Puerto Rico': 'PRI',
        'Qatar': 'QAT',
        'Romania': 'ROU',
        'Russian Federation': 'RUS',
        'Rwanda': 'RWA',
        'Réunion': 'REU',
        'Saint Barthélemy': 'BLM',
        'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
        'Saint Kitts and Nevis': 'KNA',
        'Saint Lucia': 'LCA',
        'Saint Martin (French part)': 'MAF',
        'Saint Pierre and Miquelon': 'SPM',
        'Saint Vincent and the Grenadines': 'VCT',
        'Samoa': 'WSM',
        'San Marino': 'SMR',
        'Sao Tome and Principe': 'STP',
        'Saudi Arabia': 'SAU',
        'Senegal': 'SEN',
        'Serbia': 'SRB',
        'Seychelles': 'SYC',
        'Sierra Leone': 'SLE',
        'Singapore': 'SGP',
        'Sint Maarten (Dutch part)': 'SXM',
        'Slovakia': 'SVK',
        'Slovenia': 'SVN',
        'Solomon Islands': 'SLB',
        'Somalia': 'SOM',
        'South Africa': 'ZAF',
        'South Georgia and the South Sandwich Islands': 'SGS',
        'South Sudan': 'SSD',
        'Spain': 'ESP',
        'Sri Lanka': 'LKA',
        'Sudan': 'SDN',
        'Suriname': 'SUR',
        'Svalbard and Jan Mayen': 'SJM',
        'Sweden': 'SWE',
        'Switzerland': 'CHE',
        'Syrian Arab Republic': 'SYR',
        'Taiwan, Province of China': 'TWN',
        'Tajikistan': 'TJK',
        'Tanzania, United Republic of': 'TZA',
        'Thailand': 'THA',
        'Timor-Leste': 'TLS',
        'Togo': 'TGO',
        'Tokelau': 'TKL',
        'Tonga': 'TON',
        'Trinidad and Tobago': 'TTO',
        'Tunisia': 'TUN',
        'Turkey': 'TUR',
        'Turkmenistan': 'TKM',
        'Turks and Caicos Islands': 'TCA',
        'Tuvalu': 'TUV',
        'Uganda': 'UGA',
        'Ukraine': 'UKR',
        'United Arab Emirates': 'ARE',
        'United Kingdom': 'GBR',
        'United States': 'USA',
        'United States Minor Outlying Islands': 'UMI',
        'Uruguay': 'URY',
        'Uzbekistan': 'UZB',
        'Vanuatu': 'VUT',
        'Venezuela, Bolivarian Republic of': 'VEN',
        'Viet Nam': 'VNM',
        'Virgin Islands, British': 'VGB',
        'Virgin Islands, U.S.': 'VIR',
        'Wallis and Futuna': 'WLF',
        'Western Sahara': 'ESH',
        'Yemen': 'YEM',
        'Zambia': 'ZMB',
        'Zimbabwe': 'ZWE'
 }

## Check ##
# to check your code, run:
# python -m countries
if __name__=="__main__":
    print(trans)
